trigger: none

pr:
- Dev_Branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/install-dependencies.yaml

  # Scripts for running all tests in a file and to run tests based on test case name (integration testing)
  - script: |
      robot --output results/logs/output_stinapalle_test.xml --log results/logs/log_stinapalle_test.html --report results/logs/report_stinapalle_test.html tests/stinapalle_tests.robot
    displayName: 'Run Test File "Kim"'

  - script: |
      robot --test "Test Book Herbivore Safari with Feeding on Weekend" --output results/logs/output_kim_family_tests.xml --log results/logs/log_kim_family_tests.html --report results/logs/report_kim_family_tests.html tests/
    displayName: 'Run Specific Tests'

  # Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-develop'
    displayName: 'Publish Robot Framework Reports'


